### ISSUE TITLE
Mocking a populated result

### ISSUE THREAD

**Issue by gavinhenderson** [alonronin/mockingoose#48]
This issue is the as #38.

It was said:
> it is not suppose to populate as it is just a mock, so if you use populate, mock the complete result

However, when I mock the populated result it returns a version without the field that is wanting to be 'populated'.

Example: 
```js
mockingoose.Passport.toReturn({
     name: 'test',
     creator: { password: '123'},
}, 'findOne');

Passport.findOne({ accessId })
    .populate('creator')
    .exec((err, passport) => {
        console.log(passport); // => { name:'test' }
    })
});
```

**Comment by andreialecu** [comment]
This indeed seems to be a problem. 

Mongoose seems to sanitize the object to remove `creator` from the returned document, probably because it doesn't match the schema - so the mock won't make it through.

**Comment by gavinhenderson** [comment]
Is there a way to solve this? or is it not currently a priority?

**Comment by alonronin** [comment]
you can now use a function to mock, #50 should solve this

**Comment by andreialecu** [comment]
@alonronin it doesn't though. If you try the code @gavinhenderson posted, the resulting object is indeed missing `creator`. Mongoose is doing something to remove it from the returned DocumentModel. Probably because it doesn't match the schema.

**Comment by gavinhenderson** [comment]
@andreialecu You can see my schema here if that helps debug.

https://github.com/Open-Communication/DigitalCommunicationPassports/tree/master/server/schema

**Comment by alonronin** [comment]
@andreialecu @gavinhenderson did you use the new function as mock feature? as I recall this method does not goes thru Model.create of mongoose.

**Comment by andreialecu** [comment]
The function as mock feature works the same as the object as mock feature as far as returning goes, so it does go through `Model.create`. 

See this branch for a failing test:

https://github.com/andreialecu/mockingoose/tree/populate-bug

**Comment by andreialecu** [comment]
From my initial go at debugging this, it seems like we need to intercept something deeper inside mongoose in order to fix this. 

Perhaps an alternative would be to add a parameter to the API like:

```
        mockingoose.User.toReturn(() => docObj, 'findOne', { noModel: true });
```

Which would prevent the mock from being passed through the Model constructor here: https://github.com/alonronin/mockingoose/blob/master/src/index.ts#L130 and instead just return it as it is.

**Comment by andreialecu** [comment]
Also note that in the failing test above, removing `.populate('foo')` doesn't help, which confirms that Mongoose removes the property because it doesn't match the schema. So it's not safe to assume that one could put anything in the `toReturn(object)` call and expect it to come out the other way intact.

The proper way to fix this would be to ensure `.populate('foo')`, makes Mongoose call `.find` on the Foo model, which we can then mock with `toReturn`. But it seems like Mongoose is **not** calling any of the `find*()` methods on the Foo model when `.populate` is used on the parent document.

**Comment by alonronin** [comment]
Yes, we are making `new Model(item)` for each mock.

You can try to set the schema's option `strict` to false, only for the test:

```js
import User from './UserSchema';

User.set('strict', false);

const Model = mongoose.model('User', User);

mockingoose(User).toReturn(doc); // doc with the populated item
```

**Comment by andreialecu** [comment]
`strict` only seems to work with properties that are not part of the schema. Since `foo` is in the schema here, the type mismatch still makes Mongoose delete it. Changing from`foo` to `foo2` inside the test, setting `strict` to `false` and **not** renaming or adding `foo2` in the schema makes the test pass, so `foo2` is retained, but `foo` is not.

**Comment by alonronin** [comment]
Ok, I see. you Need to change the type of the path in the schema for the test:

```js
User.schema.path('foreignKey', Object);

      const doc = {
        email: 'test@mail.com',
        name: 'Name',
        saveCount: 1,
        foreignKey: {
          _id: '5ca4af76384306089c1c30ba',
          name: 'test',
          value: 'test'
        }
      };

      mockingoose(User).toReturn(doc);

      const result = await User.find();

      expect(result).toMatchObject(doc);
```

I added a test.

**Comment by gavinhenderson** [comment]
@alonronin Sorry im not sure I follow, what do I need to change in my initial example to achieve the mocking of the populate?

My initial example:
```
mockingoose.Passport.toReturn({
     name: 'test',
     creator: { password: '123'},
}, 'findOne');

Passport.findOne({ accessId })
    .populate('creator')
    .exec((err, passport) => {
        console.log(passport); // => { name:'test' }
    })
});
```

I would like it to be:
```
mockingoose.Passport.toReturn({
     name: 'test',
     creator: { password: '123'},
}, 'findOne');

Passport.findOne({ accessId })
    .populate('creator')
    .exec((err, passport) => {
        console.log(passport); // => { name:'test', creator: { password: '123' } }
    })
});
```

**Comment by andreialecu** [comment]
Try Passport.schema.path('creator', Object);` before the `findOne()` call.

**Comment by adithyakrish3** [comment]
Hello,

Sorry for being late to the party. 
What is the fix here? How to mock .populate() in the already mocked result?
Can someone please explain?

**Comment by FellipeMaia** [comment]
This structure worked for me
@adithyakrish3 

const doc = {
  email: 'test@mail.com',
  name: 'Name',
  saveCount: 1,
  **foreignKeys**:[]
};

 const  foreignKey = {
    _id: '5ca4af76384306089c1c30ba',
    name: 'test',
    value: 'test'
  }

doc.foreignKey.push(foreignKey)

mockingoose(User).toReturn("findOne",doc);

User.schema.path(**'foreignKey',** Object);
const result = await User.findOne({}).populate( **''foreignKey"** );

expect(result).toEqual(doc);
