### ISSUE TITLE
Doesn't work with ts-jest

### ISSUE THREAD

**Issue by sandorvasas** [alonronin/mockingoose#65]
I'm getting `TypeError: Cannot set property _id of [object Object] which has only a getter`
With the following simple test:
```ts
import mockingoose from 'mockingoose'
import { TeamModel } from 'models/Team'
import {  getTeams } from './testdb'

describe('Mockingoose Population', () => {

  beforeEach(() => {
    mockingoose(TeamModel).toReturn(getTeams(), 'find')
  })

  test('TeamModel find returns pre-defined teams', async () => {
    const teams = await TeamModel.find({})
    expect(teams).toHaveLength(1)
    const target = getTeams()[0]
    expect(teams[0].toJSON()).toEqual(target)
  })

})

```

**Comment by stieg** [comment]
@sandorvasas It would probably help if you included what `getTeams` returns as well as what `TeamModel` schema looks like .  There is no way for us to help you otherwise.  I know we have mockingoose working with ts-jest internally so it is possible.  Based on the error message I would say your issue appears to come from the output of `getTeams` function.
